spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /$\{segment}
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/projects/**
          filters:
            - RewritePath=/projects/(?<segment>.*), /$\{segment}
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/tests/**
          filters:
            - RewritePath=/tests/(?<segment>.*), /$\{segment}
        - id: bug-tracking-service
          uri: lb://bug-tracking-service
          predicates:
            - Path=/bugs/**
          filters:
            - RewritePath=/bugs/(?<segment>.*), /$\{segment}
        - id: release-service
          uri: lb://release-service
          predicates:
            - Path=/releases/**
          filters:
            - RewritePath=/releases/(?<segment>.*), /$\{segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
