spring:
  application:
    name: release-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name} # Tự động theo tên service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.aptech.common.event.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:mysql://localhost:3306/release_service_db
    username: root
    password: example@123!
  # jpa:
  #   hibernate:
  #     ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8085
