spring:
  application:
    name: test-service
  kafka:
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.aptech.common.event"
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.HashMap
    listener:
      ack-mode: manual

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:mysql://localhost:3306/test_service_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: example@123!
  jpa:
    # hibernate:
    #   ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083
jwt:
  public-key: classpath:rsa/public.pem
