spring:
  application:
    name: user-service
  kafka:
    listener:
      ack-mode: manual
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.aptech.common.event"
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.HashMap
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:mysql://localhost:3306/UserServiceFix
    username: root
    password: example@123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081

jwt:
  private-key: classpath:rsa/private.pem
  public-key: classpath:rsa/public.pem
